### ISSUE TITLE
Assistance compiling

### ISSUE THREAD

**Issue by geojitsu** [tahull/OpenOCDModFiles#1]
https://github.com/tahull/OpenOCDModFiles/blob/0b9fbb970d51dd962ed475141809c06b7c495fe5/configure.ac#L42

Hi tahull, could you assist me compiling this patch into OpenOCD?  The OpenOCD devs never worked this into any of their builds.  You can reach me at brokincognito _at_ gmail .  Your help would be greatly appreciated

**Comment by tahull** [comment]
Hi, here's the build guide [https://gnu-mcu-eclipse.github.io/openocd/build-procedure/](https://gnu-mcu-eclipse.github.io/openocd/build-procedure/)
start here:
[https://gnu-mcu-eclipse.github.io/developer/build-binaries-prerequisites-xbb/](https://gnu-mcu-eclipse.github.io/developer/build-binaries-prerequisites-xbb/)
then:
[https://github.com/gnu-mcu-eclipse/openocd-build/](https://github.com/gnu-mcu-eclipse/openocd-build/)

I think only the .c files are needed. The configure.ac can be left out.
Ill try building this later, and update this comment.

**Comment by geojitsu** [comment]
Man, thanks so much .. I feel so gimped using Keil IDE lol.  I want so
badly for tm4c to run in platform io

**Comment by tahull** [comment]
This seems to be fixed for Windows by the libusb people now. The issue was in libusb showing two devices, one that cant be opened, and one that can, and openocd implementation would try to open the first device instance and fail. I see libusb 1.0.22 fixed this issue, previous versions has this problem. 
gnu-mcu-eclipse OpenOCD 0.10.0-12 uses libusb 1.0.22 now
[https://gnu-mcu-eclipse.github.io/openocd/releases/](https://gnu-mcu-eclipse.github.io/openocd/releases/)

download the newest gnu-mcu-openocd 32 or 64 bit zip, extract and open a terminal to the `\GNU MCU Eclipse\OpenOCD\0.10.0-12-20190422-2015\bin` folder
with tm4c on, try to open an interface
`openocd -f board/ek-tm4c123gxl.cfg`
If it looks like below, then debugging should work
![opentm4c](https://user-images.githubusercontent.com/4296961/57339133-3a554800-70e5-11e9-8bb1-d57ffd553f37.png)

**Comment by geojitsu** [comment]
C:\Users\xxxx\Downloads\gnu-mcu-eclipse-openocd-0.10.0-12-20190422-2015-win64\GNU
MCU Eclipse\OpenOCD\0.10.0-12-20190422-2015\bin>openocd -f
board/ek-tm4c123gxl.cfg
GNU MCU Eclipse OpenOCD, 64-bitOpen On-Chip Debugger
0.10.0+dev-00593-g23ad80df4 (2019-04-22-20:25)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The
results might differ compared to plain JTAG/SWD
adapter speed: 500 kHz
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : RCLK (adaptive clock speed)
Error: open failed

Still no luck for me .  Is there a particular driver you're using for the
tm4c?

**Comment by tahull** [comment]
I used this driver, on Windows 10
[Stellaris® ICDI Drivers - Current](http://www.ti.com/tool/stellaris_icdi_drivers)

Try:
- changing/updating your driver
- check how libusb see's your device
- unlock your tm4c

Here's how libusb-1.0.21 and previous showed the tm4c dev board for me. Two devices, one that cant be claimed
![libusb-1 0 21 problem](https://user-images.githubusercontent.com/4296961/57414729-2c1f2e80-71ae-11e9-85fb-9d9d8c47d16d.png)

Here's libusb-1.0.22. One device. Interface 2 is the one thats needed
![libusb-1 0 22](https://user-images.githubusercontent.com/4296961/57414746-42c58580-71ae-11e9-9cd3-61bca59f5465.png)

Try my [python script ](https://github.com/tahull/Python-projects/tree/master/usb_scan) you can comment out tests 2-4 in `def print_dev(device):` for simplified result.
It needs `pip install libusb1` and [1.0.22 libusb dll](https://github.com/libusb/libusb/releases) put MS32/libusb-1.0.22.dll in same folder with python script and run `python list_dev.py 1cbe 00fd`

Try flashing/debugging on your keil. If keil cant communicate with the device, then the device might be locked. There's some lock/protection registers on tm4c if accidently set, could leave the device locked.
It can be unlocked with [TI's lm flash tool](http://www.ti.com/tool/LMFLASHPROGRAMMER) utilities tab

**Comment by geojitsu** [comment]
[all-devs.txt](https://github.com/tahull/OpenOCDModFiles/files/3160070/all-devs.txt)


thanks so much for helping.  No luck yet, i was able to run your script but i dont see TI devices showing up in list.  I'm able to debug on keil . I'm currently building a UART project and i have output to the console from the uC (communicating over serial to PC).  I attached the list_dev output.

Are these what your stellaris drivers look like?
![image](https://user-images.githubusercontent.com/2546231/57423245-30b10a80-71e1-11e9-810b-9218c4e4204e.png)

**Comment by tahull** [comment]
In your list its the device with ID 1cbe:00fd
It shows it couldn't open any interface

> Bus 001 Device 024: ID 1cbe:00fd
>   Could not Open Device 1cbe:fd
> .
> .
> .
> attempting to claim interfaces on device
> could not claim:  0
> could not claim:  1
> could not claim:  2
> could not claim:  3

Maybe you have an older driver. The Stellaris® ICDI Drivers - Current shows as:
![driver-16a](https://user-images.githubusercontent.com/4296961/57427140-884a7880-71d7-11e9-9a43-bf958a445f00.png)

If your driver icdi driver doesnt show as 2.0.7922
Try uninstall device and check the delete driver software for this device, and install the Stellaris® ICDI Drivers - Current
![delete-device](https://user-images.githubusercontent.com/4296961/57427168-a3b58380-71d7-11e9-9efd-148ede4decc9.png)

**Comment by geojitsu** [comment]
Looks like i have same version .. so weird .  maybe I can find some clues in event logs .. wonder if it's being blocked by something (i dont use A/V software though).

![image](https://user-images.githubusercontent.com/2546231/57428084-b4c0bd80-71f4-11e9-9cf8-cd0a114b7bb5.png)

![image](https://user-images.githubusercontent.com/2546231/57428093-bee2bc00-71f4-11e9-9d57-22fc07500085.png)

**Comment by tahull** [comment]
Do you connect to it through a USB hub?
I noticed your TI device shows up as

> Bus 001 Device 024:

The Device 024 is strange. It should be Device 001 I think. Check your device manager for old stellaris or ICDI or TI device drivers.
Old and inactive drivers will show when you set "show hidden"
![show-hidden](https://user-images.githubusercontent.com/4296961/57435322-f00dbd00-71f1-11e9-8470-752b6250bafc.png)
And check under usb serial bus controllers for USB Composite Device with VID 1CBE & PID 00FD
![usb composite](https://user-images.githubusercontent.com/4296961/57435754-08caa280-71f3-11e9-87ff-ebc2462b5d09.png)

Have you tried TI's free Code Composer (no code size limit, debugging support) or Energia (arduino like, but probably doesn't have hardware debugging)

**Comment by geojitsu** [comment]
No not connecting through hub but I wonder if this motherboard has some
kind of USB hub on their chipset or something.  Maybe that's preventing it
from getting direct access. I'll swap around to all the diff usb ports
today and see if i have any luck!  :)

**Comment by tahull** [comment]
This is old, but I think you're right, its possibly your motherboards USB host controller, how libusb <-> winusb are communicating with the controller. If you're still interested in solving that, libusb group might be interested in your particular problem, if you haven't tried them already [https://github.com/libusb/libusb/issues](https://github.com/libusb/libusb/issues)
